springbootwebfluxjjwt:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 600000
  password:
    encoder:
      secret: mysecreethhhhhhhhwaa
      iteration: 33
      keylength: 256